# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

lm_cpp_fit <- function(X, Y, eps, max_iter, lr) {
    .Call(`_lmCpp_lm_cpp_fit`, X, Y, eps, max_iter, lr)
}

