// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// lm_cpp_fit
arma::colvec lm_cpp_fit(arma::mat X, arma::colvec Y, double eps, int max_iter, double lr);
RcppExport SEXP _lmCpp_lm_cpp_fit(SEXP XSEXP, SEXP YSEXP, SEXP epsSEXP, SEXP max_iterSEXP, SEXP lrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type Y(YSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type lr(lrSEXP);
    rcpp_result_gen = Rcpp::wrap(lm_cpp_fit(X, Y, eps, max_iter, lr));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_lmCpp_lm_cpp_fit", (DL_FUNC) &_lmCpp_lm_cpp_fit, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_lmCpp(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
